### PR TITLE
DATA-6885 Support more data types in IO explain plan

### PR DESCRIPTION
**Pull request by JamesRTaylor**
Please review, @nishantrayan .

### CODE REVIEW

**Comment by nishantrayan** [comment]
@JamesRTaylor  is this different from : https://github.com/lyft/presto/pull/6

**Comment by JamesRTaylor** [comment]
@nishantrayan - #6 is for lyft-stable-0.210 branch, this is for lyft-stable-0.211 branch. The code itself is the same.

**Comment by nishantrayan** [comment]
👍  any reason you closed this @JamesRTaylor   https://github.com/prestodb/presto/pull/11501
also wondering if there is any easy way to test this through unit tests.

**Comment by JamesRTaylor** [comment]
I'll add some unit tests to the other EXPLAIN (TYPE IO) unit tests for the new types that are now supported. In the meantime, I'll go ahead and merge this to our stable fork.

**Comment by nishantrayan** [comment]
SG @JamesRTaylor  let me know if any of the steps in getting presto deployed is unclear. Good place to start might be
https://github.com/lyft/prestoinfra/blob/master/README.md#update-prestoinfrapresto-from-stable-branch

**Comment by JamesRTaylor** [comment]
🚀

**Pull request merged**
